# Development specific values for chimoney-rafiki chart.
# These values override the defaults in values.yaml.

global:
  environment: dev

rafikiAuth:
  replicaCount: 1
  image:
    tag: v1.0.0-alpha.20 # Or a dev-specific tag

rafikiBackend:
  replicaCount: 1
  image:
    tag: v1.0.0-alpha.20 # Or a dev-specific tag

nginx:
  replicaCount: 1
  config:
    serverNameIlp: "ilp-sandbox.chimoney.com"
    serverNameAuth: "auth-ilp-sandbox.chimoney.io"
    graphqlAllowedIps: # More permissive for dev if needed
      - "35.160.120.126"
      - "44.233.151.27"
      - "34.211.200.85"
      - "34.66.77.227"

ingress:
  hosts:
    ilp:
      host: ilp-sandbox.chimoney.com
    auth:
      host: auth-ilp-sandbox.chimoney.io
  # annotations:
  # alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:your-region:your-account-id:certificate/dev-certificate-id
