{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chimoney-rafiki.componentFullname" (dict "componentName" .Values.redis.name "context" .) }}
  labels:
    {{- include "chimoney-rafiki.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.redis.name }}
spec:
  type: {{ .Values.redis.service.type }}
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "chimoney-rafiki.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.redis.name }}
{{- end }}
