{{- if .Values.redis.enabled }}
apiVersion: {{ include "deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "chimoney-rafiki.componentFullname" (dict "componentName" .Values.redis.name "context" .) }}
  labels:
    {{- include "chimoney-rafiki.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.redis.name }}
spec:
  replicas: {{ .Values.redis.replicaCount }}
  selector:
    matchLabels:
      {{- include "chimoney-rafiki.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ .Values.redis.name }}
  template:
    metadata:
      labels:
        {{- include "chimoney-rafiki.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: {{ .Values.redis.name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.redis.name }}
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          ports:
            - name: redis
              containerPort: {{ .Values.redis.ports.redis }}
              protocol: TCP
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
      restartPolicy: Always
{{- end }}
