{{- if .Values.kubernetesSecrets.rafikiAuth.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.kubernetesSecrets.rafikiAuth.name }}
  labels:
    {{- include "iaas-rafiki.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $.Values.rafikiAuth.name }}
type: Opaque
data:
  {{- with .Values.kubernetesSecrets.rafikiAuth.data }}
  {{- toYaml . | nindent 2 }}
  {{- else }}
  # Placeholder: Secrets data should be populated via Pulumi, --set, or a secure values file.
  # Example:
  # RAFIKI_AUTH_DATABASE_URL: "changeme" # Base64 encoded
  placeholder: "ensure_secrets_are_provided"
  {{- end }}
---
{{- end }}
{{- if .Values.kubernetesSecrets.rafikiBackend.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.kubernetesSecrets.rafikiBackend.name }}
  labels:
    {{- include "iaas-rafiki.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $.Values.rafikiBackend.name }}
type: Opaque
data:
  {{- with .Values.kubernetesSecrets.rafikiBackend.data }}
  {{- toYaml . | nindent 2 }}
  {{- else }}
  # Placeholder: Secrets data should be populated via Pulumi, --set, or a secure values file.
  placeholder: "ensure_secrets_are_provided"
  {{- end }}
{{- end }}
